organizations:
  - name: "jpedroza-dev"
    email: "pedrozajoaopedro@gmail.com"
    workspaces:
      - name: "ansible-vault-example"
        variables:
          - key: "root_token"
            value: "root"
            description: "Root token do Vault para acesso do provider."
        tags:
          - ansible
          - vault
